import { FilamentSpool } from "./types";

const now = new Date().toISOString();

export const defaultSpools: FilamentSpool[] = [
  // Bambu Lab PLA Aero - White (existing, ~50%)
  {
    id: "spool-8UW7",
    brand: "Bambu Lab",
    material: "PLA Aero",
    colorName: "White",
    colorHex: "FFFFFF",
    totalWeightGrams: 1000,
    remainingWeightGrams: 500,
    costPerSpool: 0,
    currency: "USD",
    notes: "",
    lowStockThresholdGrams: 200,
    isArchived: false,
    createdAt: now,
    updatedAt: now,
  },
  // Bambu Lab PLA Aero - White (existing, ~50%)
  {
    id: "spool-NFYT",
    brand: "Bambu Lab",
    material: "PLA Aero",
    colorName: "White",
    colorHex: "FFFFFF",
    totalWeightGrams: 1000,
    remainingWeightGrams: 500,
    costPerSpool: 0,
    currency: "USD",
    notes: "",
    lowStockThresholdGrams: 200,
    isArchived: false,
    createdAt: now,
    updatedAt: now,
  },
  // Bambu Lab PLA Aero - White (NEW, 100%)
  {
    id: "spool-AERO-NEW1",
    brand: "Bambu Lab",
    material: "PLA Aero",
    colorName: "White",
    colorHex: "FFFFFF",
    totalWeightGrams: 1000,
    remainingWeightGrams: 1000,
    costPerSpool: 0,
    currency: "USD",
    notes: "New spool",
    lowStockThresholdGrams: 200,
    isArchived: false,
    createdAt: now,
    updatedAt: now,
  },
  // Bambu Lab PLA Aero - White (NEW, 100%)
  {
    id: "spool-AERO-NEW2",
    brand: "Bambu Lab",
    material: "PLA Aero",
    colorName: "White",
    colorHex: "FFFFFF",
    totalWeightGrams: 1000,
    remainingWeightGrams: 1000,
    costPerSpool: 0,
    currency: "USD",
    notes: "New spool",
    lowStockThresholdGrams: 200,
    isArchived: false,
    createdAt: now,
    updatedAt: now,
  },
  // eSUN 3D PLA-LW - Natural (40%)
  {
    id: "spool-LLQP",
    brand: "eSUN",
    material: "PLA-LW",
    colorName: "Natural",
    colorHex: "E8DCC8",
    totalWeightGrams: 1000,
    remainingWeightGrams: 400,
    costPerSpool: 0,
    currency: "USD",
    notes: "",
    lowStockThresholdGrams: 200,
    isArchived: false,
    createdAt: now,
    updatedAt: now,
  },
  // eSUN 3D PLA-LW - Natural (100%)
  {
    id: "spool-GYVA",
    brand: "eSUN",
    material: "PLA-LW",
    colorName: "Natural",
    colorHex: "E8DCC8",
    totalWeightGrams: 1000,
    remainingWeightGrams: 1000,
    costPerSpool: 0,
    currency: "USD",
    notes: "",
    lowStockThresholdGrams: 200,
    isArchived: false,
    createdAt: now,
    updatedAt: now,
  },
  // ELEGOO PLA RAPID PLA Plus - Grey (100%)
  {
    id: "spool-GJ3N",
    brand: "ELEGOO",
    material: "PLA RAPID PLA Plus",
    colorName: "Grey",
    colorHex: "808080",
    totalWeightGrams: 1000,
    remainingWeightGrams: 1000,
    costPerSpool: 0,
    currency: "USD",
    notes: "",
    lowStockThresholdGrams: 200,
    isArchived: false,
    createdAt: now,
    updatedAt: now,
  },
  // ELEGOO PLA MATTE - Black (100%)
  {
    id: "spool-BXB4",
    brand: "ELEGOO",
    material: "PLA MATTE",
    colorName: "Black",
    colorHex: "1A1A1A",
    totalWeightGrams: 1000,
    remainingWeightGrams: 1000,
    costPerSpool: 0,
    currency: "USD",
    notes: "",
    lowStockThresholdGrams: 200,
    isArchived: false,
    createdAt: now,
    updatedAt: now,
  },
  // ELEGOO PETG PRO - Black (98%)
  {
    id: "spool-RY23",
    brand: "ELEGOO",
    material: "PETG PRO",
    colorName: "Black",
    colorHex: "1A1A1A",
    totalWeightGrams: 1000,
    remainingWeightGrams: 980,
    costPerSpool: 0,
    currency: "USD",
    notes: "",
    lowStockThresholdGrams: 200,
    isArchived: false,
    createdAt: now,
    updatedAt: now,
  },
  // 3idea PLA - Black (100%)
  {
    id: "spool-M1HH",
    brand: "3idea",
    material: "PLA",
    colorName: "Black",
    colorHex: "1A1A1A",
    totalWeightGrams: 1000,
    remainingWeightGrams: 1000,
    costPerSpool: 0,
    currency: "USD",
    notes: "",
    lowStockThresholdGrams: 200,
    isArchived: false,
    createdAt: now,
    updatedAt: now,
  },
  // eSUN 3D PLA-CF - Black (100%)
  {
    id: "spool-32IJ",
    brand: "eSUN",
    material: "PLA-CF",
    colorName: "Black",
    colorHex: "1A1A1A",
    totalWeightGrams: 1000,
    remainingWeightGrams: 1000,
    costPerSpool: 0,
    currency: "USD",
    notes: "",
    lowStockThresholdGrams: 200,
    isArchived: false,
    createdAt: now,
    updatedAt: now,
  },
];
